### ISSUE TITLE
希望能加上如何用cmake生成可执行文件和如何调试的教程

### ISSUE THREAD

**Issue by hanquanjushi** [USTC-CG/USTC_CG_24#2]
https://github.com/USTC-CG/USTC_CG_24/blob/main/Softwares/CMake.md
中讲了怎么用cmake进行编译，但没有如何生成可执行文件的教程(在build文件夹下cmake --build .)
此外，希望能出一个配置gdb图形化界面调试的教程
（类似于rec 链接：
https://rec.ustc.edu.cn/share/00de5ff0-6842-11ee-9cd7-e391a3853b53
密码：compile23）

**Comment by hanquanjushi** [comment]
https://www.bilibili.com/video/BV1o34y1675i/?spm_id_from=333.337.search-card.all.click&vd_source=6085eaae0659d656b3f388b126915b07
讲解了如何调试

**Comment by zhehaoli1999** [comment]
> https://github.com/hanquanjushi/computer_graphics/blob/main/Softwares/CMake.md 中讲了怎么用cmake进行编译，但没有如何生成可执行文件的教程(在build文件夹下cmake --build .) 此外，希望能出一个配置gdb图形化界面调试的教程 （类似于rec 链接： https://rec.ustc.edu.cn/share/00de5ff0-6842-11ee-9cd7-e391a3853b53 密码：compile23）

同学你好，你的第一个链接因为私有库无法打开，不过看上去就是指Softwares文件夹下的CMake.md文件。意见收到，我们来增加一下相关教程。

**Comment by hanquanjushi** [comment]
感谢！

**Comment by Jerry-Shen0527** [comment]
[这里之前写了一个](https://github.com/USTC-CG/USTC_CG_24/blob/main/Homeworks/0_cpp_warmup/documents/CMake_step_by_step/CMAKE_step_by_step.md)
